/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.study;

import com.study.App;
import org.junit.*;

import static org.junit.Assert.*;

public class AppTest {
    @BeforeClass public static void testAppBeforeClass(){
        System.out.println("Before All");
    }
    @Before
    public void testAppBefore(){
        System.out.println("Before");
    }
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        System.out.println("TEST");
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @After
    public void testAppAfter(){
        System.out.println("After");
    }
    @AfterClass
    public static void testAppAfterClass(){
        System.out.println("After All");
    }
}
